apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.name" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
#          livenessProbe:
            #ADD By developer
#            initialDelaySeconds: {{ .Values.config.initialDelaySeconds }}
#            httpGet:
#              path: /petclinic
#              port: http
#          readinessProbe:
            #ADD By developer
#            initialDelaySeconds: {{ .Values.config.initialDelaySeconds }}
#            httpGet:
#              path: /petclinic
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}              
## Added by developer
          env:
            {{- range $.Values.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- if .Values.config.enableKeyVault }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "backend.name" . }}-{{ .Release.Revision}}-secret
                  key: {{ .Values.config.key }}
            {{- end }}
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.environment }}"
          {{- if .Values.config.enableKeyVault }}
          volumeMounts:
            - mountPath: "/mnt"
              name: secrets-mount
           {{- end }}
      volumes:
        {{- if .Values.config.enableKeyVault }}
        - name: secrets-mount
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-keyvault-{{ include "backend.name" . }}-{{ .Release.Revision}}"
        {{- end }}