name: SpringTomcatbuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [agent2]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3.4.1
      with:
        java-version: '17'
        distribution: 'temurin'
          

   
    #--------------------------------------------------------------------------
    # Fetching Version from POM.xml file inside the module code for application
    #--------------------------------------------------------------------------

    - run: echo -e "\e[34m[Get pom.xml version]"
      shell: bash
    - name: Get pom.xml version
      id: get-pom-version
      shell: bash
      run: |
        chmod +x mvnw
        version=`./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout`
        value=`echo "$version" | awk -F" " '{print $2}' | awk '{print $2}'`
        echo $value
        echo "::set-output name=pom-version::$value"

    #----------------------
    # Code Packaging -> JAR
    #----------------------

    - name: Package Java application
      run: |
        echo -e "\e[34m[Package Java application]"
        chmod +x mvnw
        ./mvnw -B package
      shell: bash

    #-----------------------------------------------------------------
    # Archiving the JAR Package using upload-artifact@v1 Github Action
    #-----------------------------------------------------------------

    - run: echo -e "\e[34m[Store the JAR file]"
      shell: bash     
    - name: Java package artifact upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: petclinic.war
        path: ./target/petclinic.war
   
  
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: petclinic.war
        path: target/
        
    - name: Check WAR
      run: |
        ls -ltra
        ls -l target
      shell: bash

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 


    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ inputs.AZURE_WEBAPP_NAME }}
        slot-name: ${{ inputs.AZURE_WEBAPP_SLOT }}
        package: ./target/petclinic.war
